### PR TITLE
S3 Fetcher

### PR DESCRIPTION
**Pull request by Acivico**
I have added the functionality of being able to download content from Amazon Web Service S3

### CODE REVIEW

**Review by jmfernandez — CHANGES_REQUESTED** [review]
Could you rename `tests/wetlab2variations_execution_nxf.wfex_s3.stage` to something like `tests/wetlab2variations_execution_nxf_s3_input.wfex.stage`, please?

**Comment by Acivico** [comment]
I have already renamed it

**Review by jmfernandez — APPROVED** [review]

**Review by jmfernandez — CHANGES_REQUESTED** [review]
I have just realized that https://github.com/Acivico/WfExS-backend/blob/main/wfexs_backend/fetchers/s3.py is lacking the header describing the licence and copyright. For instance:

https://github.com/Acivico/WfExS-backend/blob/ce36095f1503c273b5c67f9bb6afeb3876f0e9a7/wfexs_backend/fetchers/pride.py#L1-L16

**Comment by Acivico** [comment]
It is already modified

**Review by jmfernandez — APPROVED** [review]
Nice!

**Review by lrodrin — APPROVED** [review]
Reviewed!

**Pull request merged**
